version: "3.7"

services:  
  mfe-auth-module:
    container_name: mfe-auth-module
    build: 
      context: ./mfe-auth-module
    networks:
      - local-network

  mfe-advisor-module:
    container_name: mfe-advisor-module
    build:  
      context: ./mfe-advisor-module
    networks:
      - local-network
    
  mfe-customer-module:
    container_name: mfe-customer-module
    build:  
      context: ./mfe-customer-module  
    networks:
      - local-network
    
  mfe-nginx-orchestrator:
    container_name: mfe-nginx-orchestrator
    build:    
      context: ./nginx
    volumes:
      - ./assets:/var/www
    ports:
      - "80:80"
    networks:
      - local-network
    depends_on:
      - mfe-auth-module
      - mfe-advisor-module
      - mfe-customer-module

networks:
  local-network: